dist: trusty
sudo: false

language: go
go:
- 1.11.1

git:
  depth: 1

stages:
- test
- name: deploy
  if: tag IS present

env:
- secure: GdjyagQF6+eCXAXFL5GegpwzxDuuMIiZDdAqG7DWMt54VhEnVFVl3Gw3Kxgx2yFYgvVmAzTW8g84obalN6rCpx33VsCTlG1nM3f5UyYoAudy6TEx5IkCZ4QpmTfNILIe0pkm7/p0O8fSEXEo9f3QaoIHarmWLlVmXXnqWUhKDeBfFMXbDzhuBFwSS3HKtNdu6WIPtLcOXAift5Y24dHqWkBnAM+IdECIBb6PZUNNggVydqlBxdp+yKupk3tZnIIZlKSGvxlclnEj00tPm2KIlUCAo2BnVMJdl6uDDOlw7HMoVqh93eYW4m2zM0bwrMIAgO8b4GB7n0/E5FD68lMzEzMQIcWC27gPUWQhT5aQoSWLHVDaejjLWMtULy2NBYAQTkdvdAm/8whSLgGDpfFrGR5xVlgJTSUtn7BN7iKXg2C0xkjoRvG1YSrBDwQ0rjSYzqhptjvLITEio0YEyJP67UzM3nAQsKSwefWLpiP8ISwG8BETS3DkgfaEEUjbx8pFWAXpGIeuBzNwjekDFaTNKImHL09k3Rtny3Mx2lV6yjmNu/YuaBMNmsC2ynHjjOlzTvpFD5QvquuHT0nqncTo8yBZR4EkDKsymI/hl+iATkXpZsEezDtAcE1a6AC5j8rRn4BYz1syDgzQ0MMe5Gu//rZNAyJKGpZRVkiTs1wNEw0=

jobs:
  include:
  - stage: test
    script: make vendor-status
  - script:
    - make tools
    - make lint
  - script: make coverage
  - stage: deploy
    script: make compile
    before_deploy:
    - chmod +x dist/*
    - test "`dist/clon_linux_amd64 version`" == "clon ${TRAVIS_TAG}"
    deploy:
      provider: releases
      api_key:
        secure: tz6e7OR9D1K/OvQYC/ROSK7vfcyp9T/x8uTURruSSNXfjIJhnfHdG+Zz8GR7Q97a+9UVfejWBLwya6hnyHOsQU0VSMcWL+fnw99ai47sUEvgpXxsBAVuZEhmjlqXjm3z2/ODfJdjXTCTBDRF4qSBldAP2eR5QT1fXmvCn19bq3IwhUx4aFb0ROAEwXPrTE6x/iB9PPWo9g5anYH6wjt6zrFEPVqZ3H4tyTX3/RP0Wkagbds1DulJrfFSM/ktaQ3H/IF1pcbhBlNCGouPkrJ1aI/17y8uGqcZendQiqI+S7lXwe1Qx7C3MEQ+XzwzOgdcye+C72OZt9pt7gxAGt8Ig1McmuHa7L9Bnak85mJgGIxTra55oZzOyVS5/6ab+ZI+Kdv1bfHdVtoP/PPFsawnx7iqmr1rSpJsMooDdeTF5JXcWtTwLDS+r//LzpeMdujHdR3Sc/OKq8K1AcQWIW0T5QqmQnNNbkmCwM9hEVfyc86qVSFwEHS4XLF9YTyGL047dQ9oUTrl55l3Xajx4JNm0vxo0X6SUFnzI4iTTFPcygu3Z8A/D8Sw+lWP8DT62EVBBw3bEMnSbx3tLUqYKZr13bIwb50rRn19y/2D1sMpA04VAkjVct2iT5lVT6ZtBr7Eu7zyT2Bj1X0tRJgOd2s1Xur4ataMOjBysqWu6O9WMbU=
      skip_cleanup: true
      file_glob: true
      file: dist/*
      on:
        tags: true
